-- DROP VIEW IF EXISTS `ztv_executionsummary`;
CREATE OR REPLACE VIEW `ztv_executionsummary` AS SELECT `zt_task`.`execution` AS `execution`,SUM(IF((`zt_task`.`isParent` = '0'),`zt_task`.`estimate`,0)) AS `estimate`,SUM(IF((`zt_task`.`isParent` = '0'),`zt_task`.`consumed`,0)) AS `consumed`,SUM(IF(((`zt_task`.`status` <> 'cancel') AND (`zt_task`.`status` <> 'closed') AND (`zt_task`.`isParent` = '0')),`zt_task`.`left`,0)) AS `left`,COUNT(0) AS `number`,SUM(IF(((`zt_task`.`status` <> 'done') AND (`zt_task`.`status` <> 'closed')),1,0)) AS `undone`,SUM(IF(`zt_task`.`isParent` = '0',`zt_task`.`consumed`,0) + IF(((`zt_task`.`status` <> 'cancel') AND (`zt_task`.`status` <> 'closed') AND (`zt_task`.`isParent` = '0')),`zt_task`.`left`,0)) AS `totalReal` FROM `zt_task` WHERE (`zt_task`.`deleted` = '0') GROUP BY `zt_task`.`execution`;
-- DROP VIEW IF EXISTS `ztv_projectsummary`;
CREATE OR REPLACE VIEW `ztv_projectsummary` AS SELECT `zt_task`.`project` AS `project`,SUM(IF((`zt_task`.`isParent` = '0'),`zt_task`.`estimate`,0)) AS `estimate`,SUM(IF((`zt_task`.`isParent` = '0'),`zt_task`.`consumed`,0)) AS `consumed`,SUM(IF(((`zt_task`.`status` <> 'cancel') AND (`zt_task`.`status` <> 'closed') AND (`zt_task`.`isParent` = '0')),`zt_task`.`left`,0)) AS `left`,COUNT(0) AS `number`,SUM(IF(((`zt_task`.`status` <> 'done') AND (`zt_task`.`status` <> 'closed')),1,0)) AS `undone`,SUM(IF(`zt_task`.`isParent` = '0',`zt_task`.`consumed`,0) + IF(((`zt_task`.`status` <> 'cancel') AND (`zt_task`.`status` <> 'closed') AND (`zt_task`.`isParent` = '0')),`zt_task`.`left`,0)) AS `totalReal` FROM `zt_task` WHERE (`zt_task`.`deleted` = '0') GROUP BY `zt_task`.`project`;
-- DROP VIEW IF EXISTS `ztv_projectstories`;
CREATE OR REPLACE VIEW `ztv_projectstories` AS SELECT `t1`.`project` AS `execution`,COUNT(1) AS `stories`,SUM(IF((`t2`.`status` = 'closed'),0,1)) AS `undone` FROM ((`zt_projectstory` `t1` LEFT JOIN `zt_story` `t2` ON((`t1`.`story` = `t2`.`id`))) LEFT JOIN `zt_project` `t3` ON((`t1`.`project` = `t3`.`id`))) WHERE ((`t2`.`deleted` = '0') AND (`t3`.`type` IN ('sprint','stage'))) GROUP BY `t1`.`project`;
-- DROP VIEW IF EXISTS `ztv_projectteams`;
CREATE OR REPLACE VIEW `ztv_projectteams` AS SELECT `zt_team`.`root` AS `execution`,COUNT(1) AS `teams` FROM `zt_team` WHERE (`zt_team`.`type` = 'execution') GROUP BY `zt_team`.`root`;
-- DROP VIEW IF EXISTS `ztv_projectbugs`;
CREATE OR REPLACE VIEW `ztv_projectbugs` AS SELECT `zt_bug`.`execution` AS `execution`,COUNT(1) AS `bugs`,SUM(IF((`zt_bug`.`resolution` = ''),0,1)) AS `resolutions`,SUM(IF((`zt_bug`.`severity` <= 2),1,0)) AS `seriousBugs` FROM `zt_bug` WHERE (`zt_bug`.`deleted` = '0') GROUP BY `zt_bug`.`execution`;
-- DROP VIEW IF EXISTS `ztv_productbugs`;
CREATE OR REPLACE VIEW `ztv_productbugs` AS SELECT `zt_bug`.`product` AS `product`,COUNT(1) AS `bugs`,SUM(IF((`zt_bug`.`resolution` = ''),0,1)) AS `resolutions`,SUM(IF((`zt_bug`.`severity` <= 2),1,0)) AS `seriousBugs` FROM `zt_bug` WHERE (`zt_bug`.`deleted` = '0') GROUP BY `zt_bug`.`product`;
-- DROP VIEW IF EXISTS `ztv_productstories`;
CREATE OR REPLACE VIEW `ztv_productstories` AS SELECT `zt_story`.`product` AS `product`,COUNT(1) AS `stories`,SUM(IF((`zt_story`.`status` = 'closed'),0,1)) AS `undone` FROM `zt_story` WHERE (`zt_story`.`deleted` = '0') GROUP BY `zt_story`.`product`;
-- DROP VIEW IF EXISTS `ztv_dayuserlogin`;
CREATE OR REPLACE VIEW `ztv_dayuserlogin` AS SELECT COUNT(1) AS `userlogin`,CAST(`zt_action`.`date` AS DATE) AS `day` FROM `zt_action` WHERE ((`zt_action`.`objectType` = 'user') AND (`zt_action`.`action` = 'login')) GROUP BY CAST(`zt_action`.`date` AS DATE);
-- DROP VIEW IF EXISTS `ztv_dayeffort`;
CREATE OR REPLACE VIEW `ztv_dayeffort` AS SELECT ROUND(SUM(`zt_effort`.`consumed`), 1) AS `consumed`,`zt_effort`.`date` AS `date` FROM `zt_effort` GROUP BY `zt_effort`.`date`;
-- DROP VIEW IF EXISTS `ztv_daystoryopen`;
CREATE OR REPLACE VIEW `ztv_daystoryopen` AS SELECT COUNT(1) AS `storyopen`,CAST(`zt_action`.`date` AS DATE) AS `day` FROM `zt_action` WHERE ((`zt_action`.`objectType` = 'story') AND (`zt_action`.`action` = 'opened')) GROUP BY CAST(`zt_action`.`date` AS DATE);
-- DROP VIEW IF EXISTS `ztv_daystoryclose`;
CREATE OR REPLACE VIEW `ztv_daystoryclose` AS SELECT COUNT(1) AS `storyclose`,CAST(`zt_action`.`date` AS DATE) AS `day` FROM `zt_action` WHERE ((`zt_action`.`objectType` = 'story') AND (`zt_action`.`action` = 'closed')) GROUP BY CAST(`zt_action`.`date` AS DATE);
-- DROP VIEW IF EXISTS `ztv_daytaskopen`;
CREATE OR REPLACE VIEW `ztv_daytaskopen` AS SELECT COUNT(1) AS `taskopen`,CAST(`zt_action`.`date` AS DATE) AS `day` FROM `zt_action` WHERE ((`zt_action`.`objectType` = 'task') AND (`zt_action`.`action` = 'opened')) GROUP BY CAST(`zt_action`.`date` AS DATE);
-- DROP VIEW IF EXISTS `ztv_daytaskfinish`;
CREATE OR REPLACE VIEW `ztv_daytaskfinish` AS SELECT COUNT(1) AS `taskfinish`,CAST(`zt_action`.`date` AS DATE) AS `day` FROM `zt_action` WHERE ((`zt_action`.`objectType` = 'task') AND (`zt_action`.`action` = 'finished')) GROUP BY CAST(`zt_action`.`date` AS DATE);
-- DROP VIEW IF EXISTS `ztv_daybugopen`;
CREATE OR REPLACE VIEW `ztv_daybugopen` AS SELECT COUNT(1) AS `bugopen`,CAST(`zt_action`.`date` AS DATE) AS `day` FROM `zt_action` WHERE ((`zt_action`.`objectType` = 'bug') AND (`zt_action`.`action` = 'opened')) GROUP BY CAST(`zt_action`.`date` AS DATE);
-- DROP VIEW IF EXISTS `ztv_daybugresolve`;
CREATE OR REPLACE VIEW `ztv_daybugresolve` AS SELECT COUNT(1) AS `bugresolve`,CAST(`zt_action`.`date` AS DATE) AS `day` FROM `zt_action` WHERE ((`zt_action`.`objectType` = 'bug') AND (`zt_action`.`action` = 'resolved')) GROUP BY CAST(`zt_action`.`date` AS DATE);
-- DROP VIEW IF EXISTS `ztv_dayactions`;
CREATE OR REPLACE VIEW `ztv_dayactions` AS SELECT COUNT(1) AS `actions`,CAST(`zt_action`.`date` AS DATE) AS `day` FROM `zt_action` GROUP BY CAST(`zt_action`.`date` AS DATE);
-- DROP VIEW IF EXISTS `ztv_normalproduct`;
CREATE OR REPLACE VIEW `ztv_normalproduct` AS SELECT * FROM `zt_product` WHERE `shadow` = 0;
-- DROP VIEW IF EXISTS `ztv_projectnotpl`;
CREATE OR REPLACE VIEW `ztv_projectnotpl` AS SELECT * FROM `zt_project` WHERE `deleted` = '0' AND `isTpl` = 0;
-- DROP VIEW IF EXISTS `ztv_tasknotpl`;
CREATE OR REPLACE VIEW `ztv_tasknotpl` AS SELECT * FROM `zt_task` WHERE `deleted` = '0' AND `isTpl` = 0;

-- DROP VIEW IF EXISTS `view_datasource_2`;
-- DROP VIEW IF EXISTS `view_datasource_3`;
-- DROP VIEW IF EXISTS `view_datasource_4`;
-- DROP VIEW IF EXISTS `view_datasource_5`;
-- DROP VIEW IF EXISTS `view_datasource_6`;
-- DROP VIEW IF EXISTS `view_datasource_10`;
-- DROP VIEW IF EXISTS `view_datasource_11`;
-- DROP VIEW IF EXISTS `view_datasource_12`;
-- DROP VIEW IF EXISTS `view_datasource_41`;
-- DROP VIEW IF EXISTS `view_datasource_54`;
-- DROP VIEW IF EXISTS `view_datasource_55`;
-- DROP VIEW IF EXISTS `view_datasource_119`;
-- DROP VIEW IF EXISTS `view_datasource_120`;
-- DROP VIEW IF EXISTS `view_datasource_121`;
-- DROP VIEW IF EXISTS `view_datasource_122`;
CREATE OR REPLACE VIEW `view_datasource_2`   AS SELECT `id`,`title` FROM `zt_story`       WHERE `deleted` = '0' AND type = 'epic';
CREATE OR REPLACE VIEW `view_datasource_3`   AS SELECT `id`,`title` FROM `zt_story`       WHERE `deleted` = '0' AND type = 'requirement';
CREATE OR REPLACE VIEW `view_datasource_4`   AS SELECT `id`,`title` FROM `zt_story`       WHERE `deleted` = '0' AND type = 'story';
CREATE OR REPLACE VIEW `view_datasource_5`   AS SELECT `id`,`name`  FROM `zt_task`        WHERE `deleted` = '0' AND vision = 'rnd';
CREATE OR REPLACE VIEW `view_datasource_6`   AS SELECT `id`,`title` FROM `zt_bug`         WHERE `deleted` = '0';
CREATE OR REPLACE VIEW `view_datasource_10`  AS SELECT `id`,`name`  FROM `zt_build`       WHERE `deleted` = '0';
CREATE OR REPLACE VIEW `view_datasource_11`  AS SELECT `id`,`name`  FROM `zt_module`      WHERE `deleted` = '0';
CREATE OR REPLACE VIEW `view_datasource_12`  AS SELECT `id`,`title` FROM `zt_productplan` WHERE `deleted` = '0';
CREATE OR REPLACE VIEW `view_datasource_41`  AS SELECT `id`,`title` FROM `zt_case`        WHERE `deleted` = '0';
CREATE OR REPLACE VIEW `view_datasource_54`  AS SELECT `id`,`name`  FROM `zt_task`        WHERE `deleted` = '0' AND vision = 'lite';
CREATE OR REPLACE VIEW `view_datasource_55`  AS SELECT `id`,`title` FROM `zt_feedback`    WHERE `deleted` = '0';
CREATE OR REPLACE VIEW `view_datasource_119` AS SELECT `id`,`name`  FROM `zt_demandpool`  WHERE `deleted` = '0';
CREATE OR REPLACE VIEW `view_datasource_120` AS SELECT `id`,`title` FROM `zt_demand`      WHERE `deleted` = '0';
CREATE OR REPLACE VIEW `view_datasource_121` AS SELECT `id`,`name`  FROM `zt_roadmap`     WHERE `deleted` = '0';
CREATE OR REPLACE VIEW `view_datasource_122` AS SELECT `id`,`title` FROM `zt_story`       WHERE `deleted` = '0';
